
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PICAT_SM(object):
    def setupUi(self, PICAT_SM):
        PICAT_SM.setObjectName("PICAT_SM")
        PICAT_SM.resize(650, 300)
        self.centralwidget = QtWidgets.QWidget(PICAT_SM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SM_Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.SM_Tabs.setObjectName("SM_Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Main_ScrollArea = QtWidgets.QScrollArea(self.tab)
        self.Main_ScrollArea.setWidgetResizable(True)
        self.Main_ScrollArea.setObjectName("Main_ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 174))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Main_VerLay = QtWidgets.QVBoxLayout()
        self.Main_VerLay.setObjectName("Main_VerLay")
        self.Main_Grid_TabButton = QtWidgets.QGridLayout()
        self.Main_Grid_TabButton.setObjectName("Main_Grid_TabButton")
        self.Main_Button_InsertRec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Main_Button_InsertRec.setMinimumSize(QtCore.QSize(30, 30))
        self.Main_Button_InsertRec.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Button_InsertRec.setFont(font)
        self.Main_Button_InsertRec.setObjectName("Main_Button_InsertRec")
        self.Main_Grid_TabButton.addWidget(self.Main_Button_InsertRec, 0, 4, 1, 1)
        self.Main_Label_Buttons = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Main_Label_Buttons.setMinimumSize(QtCore.QSize(70, 30))
        self.Main_Label_Buttons.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Main_Label_Buttons.setFont(font)
        self.Main_Label_Buttons.setObjectName("Main_Label_Buttons")
        self.Main_Grid_TabButton.addWidget(self.Main_Label_Buttons, 0, 2, 1, 1)
        self.Main_CB_Buttons = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.Main_CB_Buttons.setMinimumSize(QtCore.QSize(240, 30))
        self.Main_CB_Buttons.setMaximumSize(QtCore.QSize(240, 30))
        self.Main_CB_Buttons.setObjectName("Main_CB_Buttons")
        self.Main_Grid_TabButton.addWidget(self.Main_CB_Buttons, 0, 3, 1, 1)
        self.Main_Label_Tabs = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Main_Label_Tabs.setMinimumSize(QtCore.QSize(45, 30))
        self.Main_Label_Tabs.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Main_Label_Tabs.setFont(font)
        self.Main_Label_Tabs.setObjectName("Main_Label_Tabs")
        self.Main_Grid_TabButton.addWidget(self.Main_Label_Tabs, 0, 0, 1, 1)
        self.Main_CB_Tabs = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.Main_CB_Tabs.setMinimumSize(QtCore.QSize(120, 30))
        self.Main_CB_Tabs.setMaximumSize(QtCore.QSize(120, 30))
        self.Main_CB_Tabs.setObjectName("Main_CB_Tabs")
        self.Main_Grid_TabButton.addWidget(self.Main_CB_Tabs, 0, 1, 1, 1)
        self.Main_Button_DeleteRec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Main_Button_DeleteRec.setMinimumSize(QtCore.QSize(30, 30))
        self.Main_Button_DeleteRec.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Button_DeleteRec.setFont(font)
        self.Main_Button_DeleteRec.setObjectName("Main_Button_DeleteRec")
        self.Main_Grid_TabButton.addWidget(self.Main_Button_DeleteRec, 0, 5, 1, 1)
        self.Main_VerLay.addLayout(self.Main_Grid_TabButton)
        self.Main_HorLay_InsDel = QtWidgets.QHBoxLayout()
        self.Main_HorLay_InsDel.setObjectName("Main_HorLay_InsDel")
        self.Main_VerLay.addLayout(self.Main_HorLay_InsDel)
        self.Main_ScrollArea_Table = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.Main_ScrollArea_Table.setWidgetResizable(True)
        self.Main_ScrollArea_Table.setObjectName("Main_ScrollArea_Table")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 551, 109))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Main_Table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.Main_Table.setObjectName("Main_Table")
        self.Main_Table.setColumnCount(0)
        self.Main_Table.setRowCount(0)
        self.gridLayout_4.addWidget(self.Main_Table, 0, 0, 1, 1)
        self.Main_ScrollArea_Table.setWidget(self.scrollAreaWidgetContents_2)
        self.Main_VerLay.addWidget(self.Main_ScrollArea_Table)
        self.gridLayout_3.addLayout(self.Main_VerLay, 0, 0, 1, 1)
        self.Main_ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.Main_ScrollArea, 0, 0, 1, 1)
        self.SM_Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Tab1_ScrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.Tab1_ScrollArea.setWidgetResizable(True)
        self.Tab1_ScrollArea.setObjectName("Tab1_ScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 117, 91))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Tab1_Grid = QtWidgets.QGridLayout()
        self.Tab1_Grid.setObjectName("Tab1_Grid")
        self.Tab1_Button_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.Tab1_Button_1.setMinimumSize(QtCore.QSize(0, 30))
        self.Tab1_Button_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Tab1_Button_1.setObjectName("Tab1_Button_1")
        self.Tab1_Grid.addWidget(self.Tab1_Button_1, 0, 0, 1, 1)
        self.Tab1_Button_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.Tab1_Button_2.setMinimumSize(QtCore.QSize(0, 30))
        self.Tab1_Button_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Tab1_Button_2.setObjectName("Tab1_Button_2")
        self.Tab1_Grid.addWidget(self.Tab1_Button_2, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.Tab1_Grid, 0, 0, 1, 1)
        self.Tab1_ScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.Tab1_ScrollArea, 0, 0, 1, 1)
        self.SM_Tabs.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.SM_Tabs, 0, 0, 1, 1)
        PICAT_SM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PICAT_SM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEdit_form = QtWidgets.QMenu(self.menubar)
        self.menuEdit_form.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PICAT_SM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PICAT_SM)
        self.statusbar.setObjectName("statusbar")
        PICAT_SM.setStatusBar(self.statusbar)
        self.actionImport_from_Excel = QtWidgets.QAction(PICAT_SM)
        self.actionImport_from_Excel.setObjectName("actionImport_from_Excel")
        self.actionExport_to_Excel = QtWidgets.QAction(PICAT_SM)
        self.actionExport_to_Excel.setObjectName("actionExport_to_Excel")
        self.actionRefresh = QtWidgets.QAction(PICAT_SM)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionTabsize = QtWidgets.QAction(PICAT_SM)
        self.actionTabsize.setObjectName("actionTabsize")
        self.actionOpen_Files_Explorer = QtWidgets.QAction(PICAT_SM)
        self.actionOpen_Files_Explorer.setObjectName("actionOpen_Files_Explorer")


        self.actionAdd_exe = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_exe.setObjectName("actionAdd_exe")

        self.actionAdd_tabto = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_tabto.setObjectName("actionAdd_tabto")
        self.actionAdd_url = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_url.setObjectName("actionAdd_url")

        self.actionAdd_Folder = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_Folder.setObjectName("actionAdd_Folder")

        self.actionAdd_Seq = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_Seq.setObjectName("actionAdd_Seq")

        self.actionAdd_Proc = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_Proc.setObjectName("actionAdd_Proc")

        self.actionAdd_Desc = QtWidgets.QAction(PICAT_SM)
        self.actionAdd_Desc.setObjectName("actionAdd_Desc")

        self.actionEdit_layout = QtWidgets.QAction(PICAT_SM)
        self.actionEdit_layout.setObjectName("actionEdit_layout")

        self.actionCopy = QtWidgets.QAction(PICAT_SM)
        self.actionCopy.setObjectName("actionCopy")

        self.sht2tbl = QtWidgets.QAction(PICAT_SM)
        self.sht2tbl.setObjectName("sht2tbl")

        self.actionCopy_folder = QtWidgets.QAction(PICAT_SM)
        self.actionCopy_folder.setObjectName("actionCopy_folder")

        self.actionTab = QtWidgets.QAction(PICAT_SM)
        self.actionTab.setObjectName("actionTab")

        self.actionTabUrl = QtWidgets.QAction(PICAT_SM)
        self.actionTabUrl.setObjectName("actionTabUrl")


        self.actionTabFolder = QtWidgets.QAction(PICAT_SM)
        self.actionTabFolder.setObjectName("actionTabFolder")

        self.actionOpenTabUrl = QtWidgets.QAction(PICAT_SM)
        self.actionOpenTabUrl.setObjectName("actionOpenTabUrl")


        self.actionAbout = QtWidgets.QAction(PICAT_SM)
        self.actionAbout.setObjectName("actionAbout")

        self.actionEdit_mode = QtWidgets.QAction('Edit Mode', PICAT_SM, checkable=True)


        self.actionTab_Copy = QtWidgets.QAction(PICAT_SM)
        self.actionTab_Copy.setObjectName("actionTab_Copy")

        self.actionTab_Move = QtWidgets.QAction(PICAT_SM)
        self.actionTab_Move.setObjectName("actionTab_Move")

        self.menuFile.addAction(self.actionOpen_Files_Explorer)
        self.menuFile.addAction(self.actionOpenTabUrl)

        
        self.menuEdit.addAction(self.actionEdit_mode)
        self.menuEdit.addAction(self.actionEdit_layout)
        self.menuEdit.addAction(self.actionAdd_Seq)
        self.menuEdit.addAction(self.actionAdd_Proc)
        self.menuEdit.addAction(self.actionAdd_Desc)

        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCopy_folder)

        self.menuEdit.addAction(self.actionAdd_exe)

        self.menuEdit.addAction(self.actionAdd_url)
        self.menuEdit.addAction(self.actionAdd_Folder)
        self.menuEdit.addAction(self.actionTab)
        self.menuEdit.addAction(self.actionTabUrl)
        self.menuEdit.addAction(self.actionTabFolder)
        self.menuEdit.addAction(self.actionAdd_tabto)

        self.menuEdit.addAction(self.sht2tbl)


        self.menuEdit_form.addAction(self.actionTab_Copy)
        self.menuEdit_form.addAction(self.actionTab_Move)


        self.menuView.addAction(self.actionRefresh)
        self.menuTools.addAction(self.actionImport_from_Excel)
        self.menuTools.addAction(self.actionExport_to_Excel)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())


        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        #add self.actionTabsize to menubar
        self.menubar.addAction(self.actionTabsize)


        self.retranslateUi(PICAT_SM)
        self.SM_Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PICAT_SM)

    def retranslateUi(self, PICAT_SM):
        _translate = QtCore.QCoreApplication.translate
        PICAT_SM.setWindowTitle(_translate("PICAT_SM", "PICAT Server Manager"))
        self.Main_Button_InsertRec.setToolTip(_translate("PICAT_SM", "Insert record into batchsequence"))
        self.Main_Button_InsertRec.setText(_translate("PICAT_SM", "+"))
        self.Main_Label_Buttons.setText(_translate("PICAT_SM", "Buttons"))
        self.Main_CB_Buttons.setToolTip(_translate("PICAT_SM", "Buttons Filter"))
        self.Main_Label_Tabs.setText(_translate("PICAT_SM", "Tabs"))
        self.Main_CB_Tabs.setToolTip(_translate("PICAT_SM", "Tabs Filter"))
        self.Main_Button_DeleteRec.setToolTip(_translate("PICAT_SM", "Delete record from batchsequence"))
        self.Main_Button_DeleteRec.setText(_translate("PICAT_SM", "-"))
        self.SM_Tabs.setTabText(self.SM_Tabs.indexOf(self.tab), _translate("PICAT_SM", "Main"))
        self.Tab1_Button_1.setText(_translate("PICAT_SM", "PushButton"))
        self.Tab1_Button_2.setText(_translate("PICAT_SM", "PushButton"))
        self.SM_Tabs.setTabText(self.SM_Tabs.indexOf(self.tab_2), _translate("PICAT_SM", "Tab 1"))
        self.menuFile.setTitle(_translate("PICAT_SM", "File"))
        self.menuEdit.setTitle(_translate("PICAT_SM", "Edit"))
        self.menuEdit_form.setTitle(_translate("PICAT_SM", "Edit Form"))
        self.menuView.setTitle(_translate("PICAT_SM", "View"))
        self.menuTools.setTitle(_translate("PICAT_SM", "Tools"))
        self.menuHelp.setTitle(_translate("PICAT_SM", "Help"))
        self.actionRefresh.setText(_translate("PICAT_SM", "Refresh"))
        self.actionRefresh.setShortcut(_translate("PICAT_SM", "Ctrl+R"))
        self.actionTabsize.setText(_translate("PICAT_SM", "S"))
        #make actionTabsize text bold
        self.actionTabsize.setFont(QtGui.QFont("Times", 10, QtGui.QFont.Bold))
        #set background very light grey
        self.actionOpen_Files_Explorer.setText(_translate("PICAT_SM", "Open Files Explorer"))
        self.actionOpen_Files_Explorer.setShortcut(_translate("PICAT_SM", "Ctrl+O"))
        self.actionOpenTabUrl.setText(_translate("PICAT_SM", "Open Tab URL"))
        self.actionOpenTabUrl.setShortcut(_translate("PICAT_SM", "Ctrl+U"))
        self.actionAbout.setText(_translate("PICAT_SM", "About"))



